### ISSUE TITLE
Team names coming into HyTek Meet Manager with team code parentheticals, which we don't want

### ISSUE THREAD

**Issue by adamengst** [adamengst/hytek-import#1]
@tristanengst Team names from Webscorer all look like this:

![CleanShot 2023-12-20 at 20 45 44](https://github.com/adamengst/hytek-import/assets/36641103/f4dc40ff-c5af-493e-8f6b-460709832ab8)

However, they're coming into HyTek Meet Manager like this, with the parenthetical still in place (though truncated in one case because the overall name must be hitting a character limit).

![CleanShot 2023-12-20 at 20 46 30](https://github.com/adamengst/hytek-import/assets/36641103/51f8f939-2a39-40b3-aeb2-2ffe5bb73a44)

The problem, I believe, is that we're never parsing the team name to remove the parenthetical. Can you add some code to strip that parenthetical from the team name? Should be easy to identify it.

I don't think we care about the Short Name.

**Comment by tristanengst** [comment]
@adamengst can you comment the command you're running and the input webscorer file?

**Comment by adamengst** [comment]
This was the command I used:

`python /Users/adam/hytek-import/WebscorerToHytek.py  --webscorer /Users/adam/Downloads/sample-track.txt --hytek ~/Desktop/sample-track_hytek.txt`

**Comment by tristanengst** [comment]
Bug fixed by latest series of commits.
